STATKUBE_USERNAME: gitfred
STATKUBE_PASSWORD: 'SuP3rS3cr3!'
STATKUBE_ACCESS_TOKEN: ''
STATKUBE_REPO: kubernetes/kubernetes
STATKUBE_QUERY_EXTRA: ''
STATKUBE_USERS:
  - andreykurilin
  - asalkeld
  - dims
  - dshulyak
  - Frostman
  - gitfred
  - loles
  - nebril
  - nhlfr
  - pigmej
  - tnachen
  - vefimova
  - zefciu
# Define groups as "STATKUBE_GROUP_<custom_name>"
STATKUBE_GROUP_POZNAN:
  - gitfred
  - nebril
  - nhlfr
  - zefciu
STATKUBE_GROUP_SOMETHING:
  - nhlfr
  - dims
  - nebril
  - gitfred
STATKUBE_DATE_RANGES:
  "12-2": 2016-05-31 .. 2016-06-08
  "13-1": 2016-06-09 .. 2016-06-17
  "13-2": 2016-06-18 .. 2016-06-29
  "14":   2016-06-30 .. 2016-07-20