STATKUBE_USERNAME: gitfred
STATKUBE_PASSWORD: 'SuP3rS3cr3!'
STATKUBE_ACCESS_TOKEN: ''
STATKUBE_REPO: kubernetes/kubernetes
STATKUBE_QUERY_EXTRA: ''
STATKUBE_USERS:
  - andreykurilin
  - asalkeld
  - dims
  - dshulyak
  - Frostman
  - gitfred
  - loles
  - nebril
  - nhlfr
  - pigmej
  - tnachen
  - vefimova
  - zefciu
# Define groups as "STATKUBE_GROUP_<custom_name>"
STATKUBE_GROUP_POZNAN:
  - gitfred
  - nebril
  - nhlfr
  - zefciu
STATKUBE_GROUP_SOMETHING:
  - nhlfr
  - dims
  - nebril
  - gitfred
