STATKUBE_USERNAME: gitfred
STATKUBE_PASSWORD: ''
STATKUBE_REPO: kubernetes/kubernetes
STATKUBE_CSV_PATH: results.csv
STATKUBE_USERS:
  # - andreykurilin
  # - asalkeld
  # - dims
  # - dshulyak
  # - Frostman
  - gitfred
  - loles
  - nebril
  # - nhlfr
  # - pigmej
  # - tnachen
  # - vefimova